server:
  port: 8080
spring:
  banner:
    location: classpath:banner.txt
  web:
    resources:
      static-locations: classpath:/static/,file:C:\Users\MSB19\IdeaProjects\PGMUSICBOT\temp\public\
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: 956414531754655875
            client-secret: IN2oCMy54Da7_xh73D60rdZMygZtCcaa
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            scope:
              - identify
              - email
              - guilds
              - guilds.members.read
            redirectUri: "{baseUrl}/login/oauth2/code/discord"
            clientName: Discord Client
        provider:
          discord:
            authorizationUri: https://discordapp.com/api/oauth2/authorize
            tokenUri: https://discordapp.com/api/oauth2/token
            userInfoUri: https://discordapp.com/api/users/@me
            usernameAttribute: username
jda:
  token: ${TOKEN:OTU2NDE0NTMxNzU0NjU1ODc1.G8KIUZ.GyIp8BllgF0ASILXK7eeXlodNTYW8jzlVXdw6A}
spotify:
  userid: ${SPOTIFYUSERID:733ea23966e1482a99ef775a50f505d0}
  secret: ${SPOTIFYSECRET:9a1b5a868bd140f99eb173c8d458162a}
github:
  token: ${GITHUBTOKEN:0}
youtube:
  user: ${YTUSER:embot7573@gmail.com}
  password: ${YTPASSWORD:G^dzbyR*8a46cmsT$%5sFdtu}
tenor:
  key: AIzaSyA4hmCdzXbIhZK3Q0Nlbc0UrjgxT9FmWPo
  user: EMBot
config:

  # Nombre para el prompt de texto

  gui-prompt-name: "EMBot"

  # Mensaje nogui

  nogui: true

  nogui-title: "EMBot"

  nogui-message: "Switching to nogui mode. You can manually start in nogui mode by including the -Dnogui=true flag."

  # Deprecated
  oldFile:

  # This sets the owner of the bot
  # This needs to be the owner's ID (a 17-18 digit number)
  # https:#github.com/jagrosh/MusicBot/wiki/Finding-Your-User-ID
  owner: 498627624483028992


  # This sets the prefix for the bot
  # The prefix is used to control the commands
  # If you use !!, the play command will be !!play
  # If you do not set this, the prefix will be a mention of the bot (@Botname play)

  prefix: "@mention"


  # If you set this, it modifies the default game of the bot
  # Set this to NONE to have no game
  # Set this to DEFAULT to use the default game
  # You can make the game "Playing X", "Listening to X", or "Watching X"
  # where X is the title. If you don't include an action, it will use the
  # default of "Playing"

  game: "Escribe @MBot help en el md para mas información"

  # Discord Bot Channel

  discordChannel:


  # If you set this, it will modify the default status of bot
  # Valid values: ONLINE IDLE DND INVISIBLE

  status: ONLINE


  # If you set this to true, the bot will list the title of the song it is currently playing in its
  # "Playing" status. Note that this will ONLY work if the bot is playing music on ONE guild;
  # if the bot is playing on multiple guilds, this will not work.

  songinstatus: false


  # If you set this, the bot will also use this prefix in addition to
  # the one provided above

  altprefix : "NONE"


  # If you set these, it will change the various emojis

  success : "✅"
  warning : "💡"
  error : "🚫"
  loading : "⌚"
  searching : "🔎"


  # If you set this, you change the word used to view the help.
  # For example, if you set the prefix to !! and the help to cmds, you would type
  # !!cmds to see the help text

  help : help


  # If you set this, the "nowplaying" command will show youtube thumbnails
  # Note: If you set this to true, the nowplaying boxes will NOT refresh
  # This is because refreshing the boxes causes the image to be reloaded
  # every time it refreshes.

  nowplayingimages : false


  # If you set this, the bot will not leave a voice channel after it finishes a queue.
  # Keep in mind that being connected to a voice channel uses additional bandwith,
  # so this option is not recommended if bandwidth is a concern.

  stayinchannel : false


  # This sets the maximum amount of seconds any track loaded can be. If not set or set
  # to any number less than or equal to zero, there is no maximum time length. This time
  # restriction applies to songs loaded from any source.

  maxseconds : 0


  # This sets the amount of seconds the bot will stay alone on a voice channel until it
  # automatically leaves the voice channel and clears the queue. If not set or set
  # to any number less than or equal to zero, the bot won't leave when alone.

  alonetimeuntilstop : 0


  # This sets an alternative folder to be used as the Playlists folder
  # This can be a relative or absolute path

  playlistsfolder : "Playlists"


  # By default, the bot will DM the owner if the bot is running and a new version of the bot
  # becomes available. Set this to false to disable this feature.

  update: true

  # Default Welcome Message

  welcome : "@username Bienvenido al servidor @servername, disfruta tu estadia."

  # Default leave Message

  goodbye : "@username se ha ido."


  # Changing this changes the lyrics provider
  # Currently available providers: "A-Z Lyrics", "Genius", "MusicMatch", "LyricsFreak"
  # At the time of writing, I would recommend sticking with A-Z Lyrics or MusicMatch,
  # as Genius tends to have a lot of non-song results and you might get something
  # completely unrelated to what you want.
  # If you are interested in contributing a provider, please see
  # https:#github.com/jagrosh/JLyrics

  lyrics.default : "MusicMatch"


  # These settingsTEST allow you to configure custom aliases for all commands.
  # Multiple aliases may be given, separated by commas.
  #
  # Example 1:
  # Giving command "play" the alias "p":
  # play = [ p ]
  #
  # Example 2:
  # Giving command "search" the aliases "yts" and "find":
  # search = [ yts, find ]

  authorimages: '{
  "daft punk": "https://i.gifer.com/8hgA.gif",
  "muse": "https://cdn.discordapp.com/attachments/956807167363649556/1094734718915842239/muse.gif",
  "david bowie": "https://i.gifer.com/4RW.gif",
  "system of a down": "https://i.gifer.com/S6og.gif",
  "kavinsky": "https://i.gifer.com/8Dae.gif",
  "ac-dc": "https://i.gifer.com/EgIA.gif",
  "mgmt": "https://i.gifer.com/8giz.gif"
}'
  aliases:
    # General commands
    sendmessageas:
    settingTEST: >
      status
    # Music commands
    lyrics:
    nowplaying: >
      np,
      current
    play: >
      p
    playlists: >
      pls
    queue:
    remove : >
      delete
    scsearch :
    search : >
      ytsearch
    shuffle :
    voteskip :
    # Admin commands
    prefix : >
      setprefix
    setadmin :
    sethello :
    setgoodbye :
    addimgch :
    delimagechannel :
    setdj :
    setskip : >
      setskippercent,
      skippercent,
      setskipratio
    settc :
    setvc :
    # DJ Commands
    forceremove : >
      forcedelete,
      modremove,
      modelete
    forceskip : >
      modskip,
      skip
    movetrack : >
      move
    pause :
    playnext :
    repeat :
    skipto : >
      jumpto
    stop : >
      leave
    volume : >
      vol
  



  # Transforms are used to modify specific play inputs and convert them to different kinds of inputs
  # These are quite complicated to use, and have limited use-cases, but in theory allow for rough
  # whitelists or blacklists, roundabout loading from some sources, and customization of how things are
  # requested.
  #
  # These are NOT EASY to set up, so if you want to use these, you'll need to look through the code
  # for how they work and what fields are needed. Also, it's possible this feature might get entirely
  # removed in the future if I find a better way to do this.

  transforms:
    - key: value


  # If you set this to true, it will enable the eval command for the bot owner. This command
  # allows the bot owner to run arbitrary code from the bot's account.
  #
  # WARNING:
  # This command can be extremely dangerous. If you don't know what you're doing, you could
  # cause horrific problems on your Discord server or on whatever computer this bot is running
  # on. Never run this command unless you are completely positive what you are running.
  #
  # DO NOT ENABLE THIS IF YOU DON'T KNOW WHAT THIS DOES OR HOW TO USE IT
  # IF SOMEONE ASKS YOU TO ENABLE THIS, THERE IS AN 11/10 CHANCE THEY ARE TRYING TO SCAM YOU

  eval: false

  lyrics:
    default : "A-Z Lyrics"
    timeout : 5000
    user-agent : "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0"
    sources:
      -
        name: "A-Z Lyrics"
        search:
          url: "https://search.azlyrics.com/search.php?q=%s"
          json: false
          select: "a[href*=/lyrics/]"
        parse:
          title: "div.ringtone ~ b"
          author: "div.lyricsh b"
          content: "div.ringtone ~ div"
      -
        name: "Genius"
        search:
          url: "https://genius.com/api/search?q=%s"
          json: true
          select: "result > url"
        parse:
          title: "h1[class^=SongHeader__Title]"
          author: "a[class*=SongHeader__Artist]"
          content: "div[class^=Lyrics__Container]"
      -
        name: "Musixmatch"
        search:
          url: "https://www.musixmatch.com/search/%s"
          json: false
          select: "a.title[href*=/lyrics/]"
        parse:
          title: "h1"
          author: "h2 span a"
          content: "div.mxm-lyrics > span"
      -
        name: "LyricsFreak"
        search:
          url: "https://www.lyricsfreak.com/search.php?q=%s"
          json: false
          select: "a.song[href*=.html]"
        parse:
          title: "div#breadcrumb span > span[itemprop=title]"
          author: "h2.lyric-song-head a"
          content: "div#content"